workflows:
  react-native-workflow:
    name: React Native Build (iOS + Android)
    max_build_duration: 60
    instance_type: mac_mini_m1

    environment:
      vars:
        ENTRY_FILE: index.js
      node: 18
      xcode: 16.1
      cocoapods: 1.14.3

    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: "*"
          include: true
          source: true

    scripts:
      # 1️⃣ Install Node modules
      - name: Install Node modules
        script: |
          npm install

      # 2️⃣ Build Android release APK
      - name: Build Android release APK
        script: |
          cd android
          ./gradlew assembleRelease
          cd ..

      # 3️⃣ iOS build setup
      - name: Prepare iOS build
        script: |
          cd ios
          # Only run pod install if Podfile exists
          if [ -f Podfile ]; then
            echo "Podfile found, installing pods..."
            pod install
          else
            echo "No Podfile found, skipping pods."
          fi
          cd ..

      # 4️⃣ Build iOS IPA
      - name: Build iOS release .ipa
        script: |
          # Check if workspace exists
          if [ -f ios/US-App.xcworkspace ]; then
            echo "Using workspace for build"
            xcode-project build-ipa \
              --workspace ios/US-App.xcworkspace \
              --scheme US-App \
              --archive-directory build
          else
            echo "Using Xcode project for build"
            xcode-project build-ipa \
              --project ios/US-App.xcodeproj \
              --scheme US-App \
              --archive-directory build
          fi

    artifacts:
      - android/app/build/outputs/**/*.apk
      - build/*.ipa
      - build/**/*.ipa
      - ios/build/**/Logs/*.log

    publishing:
      email:
        recipients:
          - joejoshua99@gmail.com
