workflows:
  react-native-build:
    name: React Native Build
    max_build_duration: 60
    environment:
      vars:
        NODE_ENV: production
      node: latest
      ruby: latest
      cocoapods: default
      flutter: none
      xcode: latest
      android:
        build_tools: 33.0.2
        ndk: 25.2.9519653
        gradle: 8.1
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npx pod-install ios
      - name: Run tests
        script: |
          echo "Running tests..."
          npm test || true
      - name: Build Android
        script: |
          cd android
          ./gradlew clean
          ./gradlew assembleRelease
          cd ..
      - name: Build iOS
        script: |
          xcodebuild clean -workspace ios/US-App.xcworkspace -scheme US-App -configuration Release
          xcodebuild archive -workspace ios/US-App.xcworkspace -scheme US-App -archivePath $CM_BUILD_DIR/build/US-App.xcarchive
          xcodebuild -exportArchive -archivePath $CM_BUILD_DIR/build/US-App.xcarchive -exportOptionsPlist ios/ExportOptions.plist -exportPath $CM_BUILD_DIR/build
    artifacts:
      - build/**/*.apk
      - build/**/*.aab
      - build/**/*.ipa
    publishing:
      email:
        recipients:
          - your-email@example.com
