workflows:
  react-native-build:
    name: React Native Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        NODE_ENV: production
      node: latest
      ruby: default
      cocoapods: default
      flutter: none
      xcode: latest
    scripts:
      - name: Install dependencies & Prebuild
        script: |
          npm install
          
          # Checks if ios folder exists. If not, runs Expo Prebuild.
          if [ ! -d "ios" ]; then
            echo "⚠️ 'ios' directory not found. Running Expo Prebuild..."
            npx expo prebuild
          fi
          
          # Install Pods
          cd ios
          pod install
          cd ..

      - name: Run tests
        script: |
          echo "Running tests..."
          npm test || true

      - name: Build iOS
        script: |
          # Finds the correct workspace automatically and builds using Codemagic settings
          # This replaces the complex xcodebuild commands and fixes the plist error
          xcode-project build-ipa \
            --workspace "ios/US.xcworkspace" \
            --scheme "US" \
            --config Release

    artifacts:
      - build/**/*.apk
      - build/**/*.aab
      - build/**/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - joejoshua99@gmail.com
