workflows:
  react-native-build:
    name: React Native Build
    max_build_duration: 60
    # instance_type: mac_mini_m1 # Optional: Explicitly sets the machine type
    environment:
      vars:
        NODE_ENV: production
      node: latest
      cocoapods: default
      xcode: latest
      # REMOVED the 'android' block from here
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npx pod-install ios
      - name: Run tests
        script: |
          echo "Running tests..."
          npm test || true
      - name: Build Android
        script: |
          cd android
          # Ensure executable permission is set
          chmod +x gradlew
          ./gradlew clean
          ./gradlew assembleRelease
          cd ..
      - name: Build iOS
        script: |
          # It is often safer to specify the workspace path explicitly if it varies
          xcodebuild clean -workspace ios/US-App.xcworkspace -scheme US-App -configuration Release
          xcodebuild archive -workspace ios/US-App.xcworkspace -scheme US-App -archivePath $CM_BUILD_DIR/build/US-App.xcarchive
          xcodebuild -exportArchive -archivePath $CM_BUILD_DIR/build/US-App.xcarchive -exportOptionsPlist ios/ExportOptions.plist -exportPath $CM_BUILD_DIR/build
    artifacts:
      - build/**/*.apk
      - build/**/*.aab
      - build/**/*.ipa
    publishing:
      email:
        recipients:
          - joejoshua99@gmail.com
